ARG ELASTIC_VERSION
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}

# 플러그인 설치 예시 (필요시 주석 해제)
# RUN logstash-plugin install logstash-filter-json

# config 파일은 볼륨 마운트로 적용 (logstash.yml, pipeline)